### ISSUE TITLE
Failed to handle packet

### ISSUE THREAD

**Issue by elgskred** [MCServerTools/ServerTools-CORE#16]
This happens when I'm in the admin/moderator group.
OP colored messages is turned off.
Running Minecraft version 1.7.10
Running Opis version: 1.2.3_1.7.10
Pastebin link to log file: http://pastebin.com/6G23DCfr

I if promote myself to the admin/moderator group while on the server, everything is fine. If I try to join as admin/moderator I get the internal server error.

**Comment by matthewprenger** [comment]
Yeah thats the Opis issue that I'm pretty sure @ProfMobius already fixed. Not sure if he's released a version with the fix in it however. Nonetheless, nothing I can do about it.
