### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by khionu** [MCServerTools/ServerTools-CORE#20]
When an Op views an inventory, there is a glitch in the items, that usually straightens itself out.

If I take an item from the Player, put it in my inventory, then put it back, via dragging, it gets readded to my inventory like I picked it up. The object still exists in their inventory, however. It can be used to multiply the number of items, but, like I said, that usually fixes itself. Now, if I move via holding Shift, there is no issue.

**Comment by matthewprenger** [comment]
This sound to me like a desync issue. Sadly I can't do much since ServerTools is a server-side only mod. The /inventory command could be much better if it had a client-side counterpart.

**Comment by khionu** [comment]
Just saying.... I've been using ForgeEssentials and Cauldron + Essentials for quite a while now and never had this issue. I remember what I was experiencing those months ago, and it was consistent across the board. It wasn't just desync. Back then, I wouldn't have been able to tell you that, but I have gotten to the point where I'm a Technic Moderator on the Technic Discord server, and have given technical support to countless individuals.

This was a dupe, one I've since replicated using ProjectE, after receiving information from a player who was reporting it as a Tekkit Legends issue.
