### ISSUE TITLE
OPIS Conflicts and crashes

### ISSUE THREAD

**Issue by daviddob** [MCServerTools/ServerTools-CORE#21]
There is an issue with servertools core and Opis when both are installed if any user is added to a group even op it will kick the user out and upon rejoining they are presented with a "Internal Server Exception" warning and they cannot get in. Associated pastebin can be found here http://pastebin.com/ZkedhSQL

**Comment by matthewprenger** [comment]
Yeah it's an Opis bug that ServerTools provokes. @ProfMobius has fixed it in [this commit](https://bitbucket.org/ProfMobius/opis/commits/3f251850c83e71845a60f6399601079a3d04e855), but AFAIK it hasn't been released yet.

**Comment by matthewprenger** [comment]
@daviddob as a temporary workaround, you can disable any prefixes in chat. (OP prefixes in the `core.cfg`, and permission group prefixes)
