### ISSUE TITLE
MOTD not working

### ISSUE THREAD

**Issue by superkid333** [MCServerTools/ServerTools-CORE#29]
Hello,

I am trying to get the MOTD to work right. I am using version 1.8 of Forge and 1.8 of ServerTools CORE (only have core for 1.8). 

The MOTD does not appear when people sign on to the server. It only comes up if I type /motd. Any ideas on how to get it working? I can't find the relevant code on my end.

**Comment by matthewprenger** [comment]
This has been fixed on the 1.8.9 versions. 1.8 is EOL.
