### ISSUE TITLE
[1.7.10] Formatting in the motd stopped working randomly.

### ISSUE THREAD

**Issue by rob5251** [MCServerTools/ServerTools-CORE#31]
Originally my motd was displaying properly with colouring in the message, but now the § is parsing incorrectly and displaying a box with a question mark in it instead of registering it as a colour code.
I haven't changed anything with the motd, it just stopped working and I can't get it to work again now.

image:
http://i.imgur.com/xrAF4wQ.png

motd.txt:
http://pastebin.com/z7ZJM5FH

**Comment by matthewprenger** [comment]
Just tested and your motd.txt worked fine for me. Note you can also use `$GREEN$`, `$YELLOW$`, etc. to get colored text.

**Comment by rob5251** [comment]
Tried everything I could think of:
http://i.imgur.com/5pQNqVP.png

motd.txt:
http://pastebin.com/7ggBQbcb


Maybe its a mod conflict, but it's odd that I had no issue originally. I never added or removed any mods between the time it was working and when it decided to stop working.

My only guess is some weird mod conflict. I'll try it on its own when I get a chance later and report back.

**Comment by rob5251** [comment]
I don't know how, but I got it working again.
I think my jar file got corrupted or something, I just re-downloaded and put it back in and it was fixed.
