### ISSUE TITLE
/reloadmotd and /voice do not work for OP's nor via console in version 1.8.9-3.0.0.131

### ISSUE THREAD

**Issue by shortybsd** [MCServerTools/ServerTools-CORE#33]
On version ServerTools-CORE-1.8.9-3.0.0.131.jar

/reloadmotd and /voice do not work as well as those 2 commands in console itself.

> voice shortybsd
[01:21:16] [Server thread/INFO]: Unknown command. Try /help for a list of commands
> reloadmotd
[01:21:29] [Server thread/INFO]: Unknown command. Try /help for a list of commands

**Comment by matthewprenger** [comment]
These commands do not exist

**Comment by shortybsd** [comment]
I see that now, the commands were listed on the site. Now they aren't :P

**Comment by matthewprenger** [comment]
Yeah the voice feature went away at some point. I forget exactly why, but it was causing mod compatibility issues IIRC.
