### ISSUE TITLE
[1.8.9] /home command - but no ability to set a home point?

### ISSUE THREAD

**Issue by katubug** [MCServerTools/ServerTools-CORE#34]
I couldn't find anything in the documentation about this. Basically, there's the ability to use the /home command, but using editteleport and naming one "home" doesn't set a point for the /home command to move you to.

I'm using the 1.8.9 CORE version, since the other modules aren't updated. Am I missing something?

**Comment by matthewprenger** [comment]
`/home set` is the correct syntax.

**Comment by katubug** [comment]
Thanks very much!
